app/project/models.py
from app import db
from datetime import datetime


class Projects(db.Model):
    __tablename__ = 'app_projects'
    id = db.Column(db.Integer(), primary_key=True)

    name_project = db.Column(db.String(11), nullable=False)
    imagen = db.Column(db.String)
    description = db.Column(db.Text(), nullable=False)
    terms_conditions = db.Column(db.Text(), nullable=False)
    creation_date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    users_referreds = db.relationship('UserReferred', backref='project_created', lazy=True, cascade='all, delete-orphan',
                               order_by='desc(UserReferred.creation_date)')
    def __repr__(self):
        return f'<Projects {self.id}>'

    def save(self):
        if not self.id:
            db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    @staticmethod
    def get_all():
        return Projects.query.all()

    @staticmethod
    def order_by(column):
        return Projects.query.order_by(column).all()

    @staticmethod
    def get_by_id(id):
        return Projects.query.get(id)

    @staticmethod
    def get_by_name_project(name_project):
        return Projects.query.filter_by(name_project=name_project).first()

app/project/__init__.py
from flask import Blueprint
project_bp = Blueprint('project', __name__, template_folder = 'templates')

from . import routes

app/project/routes.py
import os
from fileinput import filename

from flask import render_template, url_for, current_app
from flask_login import login_required
from werkzeug.exceptions import abort
from werkzeug.utils import redirect, secure_filename

from app.auth.decorators import admin_required
from app.auth.forms import SignupForm
from app.auth.models import User
from app.project import project_bp
from app.project.form import ProjectForm, EditProjectForm
from app.project.models import Projects


@project_bp.route("/adminzone")
@login_required
@admin_required
def view_admin_index():
    project_created = Projects.order_by(Projects.id.desc())
    return render_template('admin-index.html', project_created=project_created)


"""@project_bp.route("/create", methods=["GET", "POST"])
@login_required
@admin_required
def add_project():

    error = ""
    message_error = ""
    form = ProjectForm()
    if form.validate_on_submit():
        name_project=form.name_project.data,
       # imagen = form.imagen.data,
        description=form.description.data,
        terms_conditions=form.terms_conditions.data,
        #image_name = None

        #if imagen:
        #    image_name = secure_filename(imagen.filename)
        #    images_dir = current_app.config['PROJECTS_IMAGES_DIR']
        #    os.makedirs(images_dir, exist_ok=True)
        #    imagen_path = os.path.join(images_dir, image_name)
        #    imagen.save(imagen_path)
        project_created=Projects(name_project=name_project, description=description, terms_conditions=terms_conditions)
        #project_created.image_name = image_name
        project_created.save()
        return redirect(url_for('project.view_admin_index'))

    formerrors = form.errors

    if formerrors != {}:
        message_error = "Error al agregar, revise los campos obligatorios."
    elif error != "":
        message_error = error
    return render_template("add-project.html", form=form, error=error, message_error=message_error)"""

@project_bp.route("/adminzone/project/create", methods=["GET", "POST"])
@login_required
@admin_required
def add_project():
    error = ""
    message_error = ""
    form = ProjectForm()
    if form.validate_on_submit():
        name_project = form.name_project.data
        # Comprobamos que no hay ya un proyecto con ese nombre
        project_created = Projects.get_by_name_project(name_project)

        if project_created is not None:
            error = f'El Nombre del projecto {name_project} ya está siendo utilizado.'
        else:
            # Creamos el usuario y lo guardamos
            project_created = Projects(
                name_project=name_project,
                description=form.description.data,
                terms_conditions=form.terms_conditions.data
            )

            project_created.save()
            return redirect(url_for('project.view_admin_index'))

    formerrors = form.errors

    if formerrors != {}:
        message_error = "Error al agregar, revise los campos obligatorios."
    elif error != "":
        message_error = error
    return render_template("add-project.html", form=form, error=error, message_error=message_error)



@project_bp.route("/adminzone/project/edit/<int:id>", methods=["GET", "POST"])
@login_required
@admin_required
def edit_project(id):
    message_error = ""
    error = ""

    projects = Projects.get_by_id(id)
    if projects is None:
        abort(404)

    form = EditProjectForm(obj=projects)

    if form.validate_on_submit():
        name_project = form.name_project.data
        project = Projects.get_by_name_project(name_project)

        if project is not None and project.id != id:
            error = f'El Nombre del projecto {name_project} ya está siendo utilizado.'
        else:
            projects.name_project = name_project,
            projects.description = form.description.data,
            projects.terms_conditions = form.terms_conditions.data,
            projects.save()
            return redirect(url_for('project.view_admin_index'))

    formerrors = form.errors

    if formerrors != {}:
        message_error = "Error al editar, por favor revise los campos obligatorios"
    elif formerrors != "":
        message_error = error

    return render_template("edit-project.html", message_error=message_error, formerrors=formerrors,projects=projects, form=form)


@project_bp.route("/adminzone/project/delete/<int:id>")
@login_required
@admin_required
def delete_project(id):
    projects = Projects.get_by_id(id)

    if projects is None:
        abort(404)
    projects.delete()
    return redirect(url_for('project.view_admin_index'))


@project_bp.route("/project/term-conditions/<int:id>", methods=["GET"] )
@login_required
def term_conditions_project(id):
    projects = Projects.get_by_id(id)
    return render_template("term-conditions-project.html", projects=projects)

app/project/templates/add-project.html
{% extends "base_template_admin.html" %}

{% block title %}Crear proyecto{{ slug_title }}{% endblock %}

{% block content %}
<div class="general-title">
        <h1>Agregar Proyecto</h1>
    </div>

    <section class="section-form">
        <div class="div-form">
            <form class="form" method="POST" enctype="multipart/form-data"  novalidate>
                <p class="form-paragraph">Por favor, ingresa los datos.</p>
                {{ form.hidden_tag() }}
                <div class="form-container">
                    <div class="form-group">
                        {% if error %}
                        <span class="span-error"><strong>Error:</strong> {{ error }}</span>
                        {% endif %}<br>
                        {{ form.name_project.label(class='form-label') }}
                        {{ form.name_project(class="form-input", id="name") }}
                        {% for error in form.name_project.errors %}
                            <span class="message-error">{{ error }}</span>
                        {% endfor %}

                    </div>
                    <div class="form-group">
                        {{ form.description.label(class='form-label') }}
                        {{ form.description(class="form-input") }}
                        {% for error in form.description.errors %}
                            <span class="message-error">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ form.terms_conditions.label(class='form-label') }}
                        {{ form.terms_conditions(class="form-input") }}
                        {% for error in form.terms_conditions.errors %}
                            <span class="message-error">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {{ form.submit(class="form-submit") }}
                </div>
            </form>
        </div>
    </section>
{% endblock %}
{% block scripts %}

{% endblock %}

app/project/templates/admin-index.html
{% extends "base_template_admin.html" %}

{% block title %}Proyectos{{ slug_title }}{% endblock %}

{% block content %}
    <div class="general-title">
        <h1>Proyectos</h1>
    </div>
    {% for project in project_created %}
   <section class="section">
            <div class="card-wrap">
                <article class="card">
                    <!--<header class="header-card">
                        <img src="{{ url_for('project.add_project', filename=project_created.image_name) }}" />
                    </header>-->
                    <footer class="footer-card">
                        <div class="text-card">
                            <a href="{{ url_for('public.add_referred', id=project.id) }}">{{project.name_project}}</a>
                            <p>{{project.description}}</p>
                        </div>
                        <div class="container-buttons">
                            <div class="links-card">
                                <a class="button-link" href="{{url_for('project.term_conditions_project', id=project.id)}}">Términos y condiciones</a>
                                <a class="button-link" href="{{ url_for('auth.view_admin', id=project.id) }}">Ir al proyecto</a>
                            </div>
                            <div class="dropdown">
                                <button class="dropdown-button">Más</button>
                                <div class="links">
                                    <a href="{{url_for('project.edit_project', id=project.id)}}" class="link-delete">Editar</a>
                                    <a href="{{url_for('project.delete_project', id=project.id)}}" class="link2-edit delete-project-btn">Eliminar</a>
                                </div>
                            </div>
                        </div>
                    </footer>
                </article>
            </div>
   </section>
    {% endfor %}

{% endblock %}
{% block scripts %}
    <script src="{{url_for('static', filename='/plugins/jquery/jquery-3.4.1.js')}}"></script>
    <script src="{{url_for('static', filename='/js/alertdelete.js')}}"></script>
{% endblock %}

app/project/templates/edit-project.html
{% extends "base_template_admin.html" %}

{% block title %}Editar proyecto {{ slug_title }}{% endblock %}

{% block content %}
<div class="general-title">
        <h1>Editar Proyect</h1>
    </div>

    <section class="section-form">
        <div class="div-form">
            <form class="form" method="POST" enctype="multipart/form-data"  novalidate>
                <p class="form-paragraph">Por favor, ingresa los datos.</p>
                {{ form.hidden_tag() }}
                <div class="form-container">
                    <div class="form-group">
                        {% if error %}
                        <span class="span-error"><strong>Error:</strong> {{ error }}</span>
                        {% endif %}<br>
                        {{ form.name_project.label(class='form-label') }}
                        {{ form.name_project(class="form-input", id="name") }}
                        {% for error in form.name_project.errors %}
                            <span class="message-error">{{ error }}</span>
                        {% endfor %}

                    </div>
                    <div class="form-group">
                        {{ form.description.label(class='form-label') }}
                        {{ form.description(class="form-input") }}
                        {% for error in form.description.errors %}
                            <span class="message-error">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ form.terms_conditions.label(class='form-label') }}
                        {{ form.terms_conditions(class="form-input") }}
                        {% for error in form.terms_conditions.errors %}
                            <span class="message-error">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {{ form.submit(class="form-submit") }}
                </div>
            </form>
        </div>
    </section>
{% endblock %}
{% block scripts %}

{% endblock %}

app/project/templates/prueba.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
     {% for project in projects %}
         <section class="section">
                    <div class="card-wrap">
                        <article class="card">
                            <header class="header-card">
                                <img src="/imagenes/vive-rio.jpeg" alt="">
                            </header>
                            <footer class="footer-card">
                                <div class="text-card">
                                    <a href="">{{project.name_project}}</a>
                                    <p>{{project.description}}</p>
                                </div>
                                <div class="links-card">
                                    <a href="">Términos y condiciones</a>
                                    <a href="">Ir al proyecto</a>
                                </div>
                            </footer>
                        </article>
                    </div>
           </section>
     {% endfor %}
</body>
</html>

app/project/templates/term-conditions-project.html
{% extends "base_template_logged.html" %}

{% block title %}Términos y condiciones{{ slug_title }}{% endblock %}

{% block content %}
     <header class="header">
        <div class="logo">
            <img src="{{url_for('static', filename='imagenes/logoBlue.png')}}" alt="Logo Inciti">
        </div>
        <button class="toggle">
            <i class="fa-solid fa-bars"></i>
        </button>
        <div class="container-links-button">
            <nav class="nav">
                <ul class="nav-links">
                        <li class="li"><a href="{{ url_for('auth.login') }}">Inicio</a></li>
                </ul>
            </nav>
        <a href="{{ url_for('auth.logout') }}" class="btn"><button>Cerrar Sesion</button></a>
        </div>
   </header>
    <div class="general-title">
        <h1>Términos y Condiciones del plan de referidos de {{projects.name_project}}</h1>
    </div>

    <section class="section-term-conditions">
        <div class="div-term-conditions">
            <p class="paragraph-term-conditions">
                {{projects.terms_conditions}}
            </p>
        </div>
    </section>
{% endblock %}